### ISSUE TITLE
Radarr keeps downloading movies over and over again

### ISSUE THREAD

**Issue by schmurnan** [mdhiggins/radarr-sma#9] opened 2020-03-27 12:56 UTC
Hey,

Firstly, this is fantastic. I’ve used your packages for a few years now, and they help my automated setup no end!

Since the changes to your docker images, though, I’ve started having an issue. I also use your sonarr-sma and I have no issues with that whatsoever (that I can see).

But radar-sma will grab a movie from my wanted list, download it, and then I can see from the logs that it will start post-processing. It moves the .mkv from SABnzbd to the correct folder, will read the autoProcess.ini, and convert the file to .m4v. But then for some reason it will download the file again, delete the old one, and keep looping through this. Last night it downloaded the same movie 14 times!  I’m not sure whether it somehow doesn’t recognise that there is a file in the folder, I have no clue, but it’s eating through data.

Have you seen this issue before, and if so can you please assist?  I’ve obviously had to make a few amendments to my setup to accommodate the new images (i.e. never used to have Download Handling enabled, but do now).

There are a few errors in the log files around DB corruption (but I have no idea if that is a known issue or not), and not sure if that’s related.

Happy to provide log files if needed, just let me know what you’d need.

Thanks again!

**Comment by mdhiggins** [comment] 2020-03-27 12:58
I've never seen this before so tough for me to help. If you turn the postRadarr script off does the problem persist? That would be the first step to identify if this might be a Radarr issue and have nothing to do with the script

If the problem goes away then post some log files and we'll have to take a look

**Comment by mdhiggins** [comment] 2020-03-27 13:06
Another thought, are you using the SABPostProcess.py script AND completed download handling from another docker container? You shouldn't use both and doing so may be triggering multiple notifications

**Comment by schmurnan** [comment] 2020-03-27 13:22
Thanks for the quick response.

I’m running the standard LinuxServer version of SABnzbd, no post-processing in there at all. All I have is the category set to ‘radarr’, and within Radarr I have SAB configured as my download client, with the corresponding ‘radarr’ label (same in Sonarr, but using ‘sonarr’ as the category).

I used to run funkypenguin’s version of SAB which had your MP4 Automator built in, so I would then run SABPostProcess.py and had completed download handling disabled in Sonarr/Radarr.  But have since switched as that image isn’t maintained anymore.

I’ve removed the postRadarr.sh script and have manually triggered a download from my Wanted list, so I’ll check the logs when it’s done and see if it throws anything up.

**Comment by schmurnan** [comment] 2020-03-27 14:40
Okay so download completed and SAB passed it back into the correct directory. Got Pushover notifications from both SAB and Radarr, and Radarr successfully updated my Plex library (as per a custom script I have setup).

Completed about 40 minutes ago, and has not tried to re-download again.

So either the issue is related to the scripts, or it’s specific to Radarr pulling downloads from my Wanted list itself, rather than me manually initiating it.

**Comment by mdhiggins** [comment] 2020-03-27 14:48
I guess its probably worthwhile to post some Radarr logs and SMA logs then and see if anything looks wrong. Has it been doing this consistently or was it a one off instance with a specific file?

**Comment by schmurnan** [comment] 2020-03-27 16:44
It's done it on the last two movies that have downloaded themselves off my Wanted list - one last weekend, one last night.

I've took an extract from sma.log and will send it over to you.  I'm trying to get one from Radarr, but I've flattened it and restarted, so don't think I have the log files anymore.

**Comment by mdhiggins** [comment] 2020-03-29 18:25
Should be fixed with recent SMA updates

**Closed as completed by mdhiggins** 2020-03-29 18:25 UTC
Labels: radarr

**Comment by schmurnan** [comment] 2020-09-11 08:06
Hey, this issue seems to have been reintroduced since the latest update. Woke up this morning to the same thing downloading five times.

**Comment by mdhiggins** [comment] 2020-09-11 08:42
Haven't made any changes recently that should impact this. Any logs?

**Comment by schmurnan** [comment] 2020-09-11 08:44
> Haven't made any changes recently that should impact this. Any logs?

I've just noticed via Portainer that there's a later release that I didn't have installed. Just installed that to see if it goes away again. In the meantime I can send you over the logs (email/Discord) for last night's activity.

**Comment by mdhiggins** [comment] 2020-09-11 18:26
Honestly I have no idea why its doing that, everything seems to be working from the script side of things as intended. Just keeps restarting without any error message to indicate why. 

Seems like your rss sync triggers things and then it just keeps trying. When a file completes and downloads and everything finishes before it restarts and tries again, see if you can see what the status of the file looks like in radarr. 
See if it detects the release, see if its still showing up in 'Wanted'. 
See if the filename listed in the radarr matches the file on your drive.

Additionally have you tested this without using postRadarr.py? Does the problem change at all? Its hard to tell if this even has anything to do with the script

**Comment by schmurnan** [comment] 2020-09-11 19:04
> Honestly I have no idea why its doing that, everything seems to be working from the script side of things as intended. Just keeps restarting without any error message to indicate why. 
> 
> 
> 
> Seems like your rss sync triggers things and then it just keeps trying. When a file completes and downloads and everything finishes before it restarts and tries again, see if you can see what the status of the file looks like in radarr. 
> 
> See if it detects the release, see if its still showing up in 'Wanted'. 
> 
> See if the filename listed in the radarr matches the file on your drive.
> 
> 
> 
> Additionally have you tested this without using postRadarr.py? Does the problem change at all? Its hard to tell if this even has anything to do with the script

I haven't tried it without postRadarr.py, no. I literally don't touch it at all, other than to pull the latest image when I get notified by Watchtower. 

I updated to the latest version earlier today and caught it trying the same download again, so I stopped it. It hasn't retried since. 

The file in question that it kept downloading isn't in my Wanted list - it was something I already had, and I think a newer/better version became available so it downloaded it via the RSS sync I think.

**Comment by mdhiggins** [comment] 2020-09-11 19:20
I'm curious if the script has anything to do with this at all so if you have a file that you can make loop try turning off postRadarr.py and see if it has any impact
